In [3]:
import tifffile
import numpy as np

def change_frame_rate(path_to_file, drop_every):
    '''
    Function that given an input path, reads the corresponding tiff file and 
    makes another tiffile droping every an specified number of frames
    
    Inputs:
        - path_to_file: String to the location of the tiff file 
        - drop_every: Integer value. 
    '''
    
    tiff_in = tifffile.TiffFile(path_to_file)
    sequence_in = tiff_in.asarray()
    sequence_out = sequence_in[path_to_file % drop_every!=0]
    with TiffWriter(path_out_tiff + "/" + file_name + ".tif", bigtiff=True) as tif:
    for frame in range(sequence.shape[0]):
        tif.save((sequence[frame]))
    return

In [13]:
test = np.arange(10)
test

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
test % 3

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0])

In [19]:
test[test % 3 != 0]

array([1, 2, 4, 5, 7, 8])